Removed `src/preload`
planetarium/9c-launcher pull request #1827
Opened 2022-08-23 17:37 UTC by PrajwalBorkar

Fixes #1759

2022-08-24 03:00 UTC, BasixKOR requested changes
`sentry.ts` contains some code which is used in various places, you may want to move it instead

2022-08-24 07:10 UTC, PrajwalBorkar commented
Can you explain where I have to move the code?

2022-08-24 07:15 UTC, BasixKOR commented
Inside `src` should be fine (for now), although I think we should make some kind of utils folder someday

2022-08-24 07:32 UTC, BasixKOR commented
`initializeSentry` is also called from few places: notably `src/renderer/render.tsx`, `src/v2/render.tsx`, and `src/main/main.tsx`. I think this PR is okay to merge once we update those references!

2022-08-24 09:14 UTC, BasixKOR approved these changes

2022-08-25 07:03 UTC, BasixKOR commented on src/sentry.ts
> +import { version } from "../../package.json";
```suggestion
import { get, app } from "./config";
import { version } from "../package.json";
```

2022-10-14 09:38 UTC, BasixKOR commented
I'm closing this PR because the communication cost of this PR is too high to justify. The PR failed to mitigate the impact of the removal (which could be looked up by checking module references and imports), and I don't think stating the points to change one by one doesn't do any better than doing it myself.

2022-10-14 09:38 UTC, closed without merging