Fix file import on importview
planetarium/9c-launcher pull request #2495
Opened 2024-10-26 04:39 UTC by kimyeonhee912

2024-10-26 04:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/planetarium/9c-launcher?pullRequest=2495) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/planetarium/9c-launcher?pullRequest=2495) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/planetarium/9c-launcher?pullRequest=2495) it.</sub>

2024-10-26 04:40 UTC, Atralupus commented
Related to https://github.com/planetarium/9c-launcher/issues/2249

2024-10-26 07:04 UTC, Atralupus approved these changes
Thanks you for your contribution!!!

2024-10-28 06:07 UTC, Akamig requested changes
다음 두가지의 문제가 있습니다.

2024-10-28 06:07 UTC, Akamig commented on src/renderer/hooks/useKeyImport.ts
> +    return utcRegex.test(fileName);
```suggestion
    return /^(?:UTC--([0-9]{4}-[0-9]{2}-[0-9]{2})T([0-9]{2}-[0-9]{2}-[0-9]{2})Z--)?([0-9a-f]{8}-(?:[0-9a-f]{4}-){3}[0-9a-f]{12})(?:.json)?$/i.test(
      fileName,
    );
```
Regex가 유효하지 않아서 조금 수정하고, const 선언 없이 바로 리턴되도록 했습니다.

2024-10-28 06:07 UTC, Akamig commented on src/renderer/hooks/useKeyImport.ts
> +        kdfparams: {
Web3 secret storage는 두가지의 [KDF](https://ko.wikipedia.org/wiki/%ED%82%A4_%EC%9C%A0%EB%8F%84_%ED%95%A8%EC%88%98)를 사용하고 있어서, PBKDF2 뿐만 아니라 Scrypt를 사용할 수도 있는데, 두개의 kdfparams 스키마가 다릅니다. 그래서 Scrypt도 지원하도록 수정되어야 합니다. 
https://ethereum.org/en/developers/docs/data-structures-and-encoding/web3-secret-storage/#scrypt

2024-10-29 04:54 UTC, Akamig commented on src/renderer/hooks/useKeyImport.ts
> +        kdfparams: {
@kimyeonhee912  잘 작동하는 거 확인했습니다. 감사합니다!

2024-10-29 04:55 UTC, Akamig approved these changes
LGTM! 수고하셨어요!

2024-10-29 04:55 UTC, merged