add offset argument to topmostblock query
planetarium/9c-launcher pull request #792
Opened 2021-07-01 05:38 UTC by area363

This PR adds an `offset` argument for `topmostblocks` query so that the launcher will show relatively confirmed blocks mined instead of blocks that are highly likely to be reorged. The initial offset is set to 100(`confirmation: 2`) but I'm open to other values for this argument value.

Also, this should be merged after https://github.com/planetarium/NineChronicles.Headless/pull/542 is merged.

2021-07-20 04:32 UTC, area363 commented
Could you take a look at this PR? It's related to https://github.com/planetarium/NineChronicles.Headless/pull/542 and it basically shows the number of blocks mined with an offset of 100 (`conf: 2`) on the launcher so that users are less confused about reorg :bow: @moreal @riemannulus @boscohyun

2021-07-20 09:45 UTC, moreal requested changes
You should bump `NineChronicles.Headless` submodule to apply this feature.

2021-07-21 01:55 UTC, area363 commented
Thanks for checking! I just updated to the latest development branch. PTAL @moreal :bow:

2021-07-21 03:16 UTC, moreal approved these changes

2021-07-21 07:02 UTC, riemannulus approved these changes

2021-07-21 07:13 UTC, merged