introduce rpc activation
planetarium/9c-launcher pull request #944
Opened 2021-09-16 14:53 UTC by ipdae

- restore missing rpc code
- activate account by signed tx

2021-09-17 04:14 UTC, BasixKOR requested changes
* I noticed some statements have braces on the next line. We write them in the same line.
* This one is just a suggestion, but I think having a function that conditionally calls `initializeRemoteHeadless` or `initializeHeadless` would be helpful.

2021-09-17 04:14 UTC, BasixKOR commented on src/renderer/views/lobby/LobbyView.tsx
> +    }
The same goes for `ended2`.

2021-09-23 02:07 UTC, ipdae commented on src/renderer/views/lobby/LobbyView.tsx
> +    }
i found this case running actual test when headless throw exception instead of handling graphql errors.

2021-09-23 06:34 UTC, BasixKOR commented
The test added with this PR is not passing. Could you check it as well?

2021-09-23 08:27 UTC, BasixKOR approved these changes

2021-09-24 05:23 UTC, merged